### ISSUE TITLE
How can I get MovieChat-1K dataset?

### ISSUE THREAD

**Issue by Aurorana** [rese1f/MovieChat#38]
You guys did a great job, I would like to use your dataset to test other models, how can I get MovieChat-1K dataset?

**Comment by Espere-1119-Song** [comment]
We will release the train and val set of MovieChat-1K next week.

**Comment by typ1012** [comment]
> We will release the train and val set of MovieChat-1K next week.

Hello, how can I download the train and val set?

**Comment by Espere-1119-Song** [comment]
Currently, feature extraction is nearly completed. However, downloading the dataset locally and uploading it to Hugging Face will still require some time, which exceeds our initial estimation. We are working diligently to expedite the data release and anticipate confirming the release by February.

**Comment by KerolosAtef** [comment]
Hello team, 
Did you release the dataset, we are in February?

**Comment by Espere-1119-Song** [comment]
Sorry, we are still solving the problem of data upload. For some reasons, we cannot upload data directly to huggingface. I will upload a few to [huggingface](https://huggingface.co/datasets/Enxin/MovieChat-1K_train) today (nearly 900 in total).

**Comment by KerolosAtef** [comment]
Okay, thanks for your help, I'm waiting.

**Comment by Espere-1119-Song** [comment]
I have uploaded the CLIP feature of one video to huggingface. Each video is extracted with 8192 frames, and each hdf5 file stores 64 frames.

**Comment by essamsleiman** [comment]
Hi @Espere-1119-Song,

Thank you for this awesome work. Can you please upload the frames for all the videos that you utilized in your evaluation. If you can't upload the frames of the videos, can you please update all the CLIP features for every video? I would really appreciate this as we are on a time crunch and need to evaluate on your benchmark as soon as possible. I really need all the videos in the eval dataset so that I have a proper evaluation of your benchmark. I am looking forward to hearing from you!

Thank you!! :)

**Comment by Espere-1119-Song** [comment]
We will release the CLIP features for every video, containing 8192 frames of each video.  Since we are holding a workshop at CVPR 2024, we will release the test set later for a fair comparison.

We are hurrying to upload the training set to HuggingFace recently. You can just use the training set in your paper for now. We found that the performance is similar if you are using the zero-shot setting.

**Comment by essamsleiman** [comment]
Hi @Espere-1119-Song thanks for getting back to me! The train set is fine for our evaluation, when will it be released? I can't find it here: https://huggingface.co/datasets/Enxin/MovieChat-1K_train

Thanks once again :)

**Comment by Espere-1119-Song** [comment]
You can find an example in ''Files'' and use this example to debug first. Eval set includes 100 videos. Although we cannot guarantee that we will upload the entire train set quickly, we can upload 100 videos within this week.

![image](https://github.com/rese1f/MovieChat/assets/77435739/1f7bcbab-3fed-4a7a-a20b-66412d5a1369)

**Comment by essamsleiman** [comment]
Thank you @Espere-1119-Song! 100 train set videos works for us. I am looking forward to the 100 videos within this week!

Best,
Essam

**Comment by Espere-1119-Song** [comment]
@essamsleiman , @KerolosAtef Over 100 videos and respective annotations have been uploaded to [Huggingface](https://huggingface.co/datasets/Enxin/MovieChat-1K_train), which can be used for evaluation.

**Comment by KerolosAtef** [comment]
Thank you very much @Espere-1119-Song , just for verification :
these are the videos which used for Table 3 in the paper (MovieChat-1K test set)

**Comment by Espere-1119-Song** [comment]
Since we are holding a workshop at CVPR 2024, we will release the test set later for a fair comparison，which is used for Table 3 in the paper. You can just use the training set in your paper for now. We found that the performance is similar if you are using the zero-shot setting.

**Comment by KerolosAtef** [comment]
Okay, thank you so much for your help

**Comment by zpx01** [comment]
@Espere-1119-Song How can I clone the dataset over SSH? When I try to use the instructions to clone the repository using git-lfs it seems to get stuck after downloading the json folder and it doesn't download the movie tar files.

**Comment by Espere-1119-Song** [comment]
Because the tar files is too big, it is normal to get stack when download the movie tar files

**Comment by Espere-1119-Song** [comment]
Currently, all annotation files have been uploaded. The feature extraction files of training videos are gradually uploading, and it is expected that all will be uploaded around mid March.

**Comment by zpx01** [comment]
@Espere-1119-Song thanks for the quick response! I was also wondering if you could point me to the code in the repository that can be used to get started with loading/using the extracted CLIP features?

**Comment by Espere-1119-Song** [comment]
Sorry, there is no code for directly loading/using the extracted features in the current repo. You can use the dataset without loading `vit_model` in https://github.com/rese1f/MovieChat/blob/main/MovieChat/models/moviechat.py. Note that we extract 8192 frames for each video.
​

**Comment by patrick-tssn** [comment]
Thank you for your exceptional contribution. Could I inquire whether it would be feasible for you to provide access to the unedited video or the frames?

**Comment by patrick-tssn** [comment]
> Sorry, the unedited video and the frames will be used for holding a workshop at CVPR 2024, we will release the test set later for a fair comparison.

Thank you for your response. Could you please provide a more precise timeline for the release of your dataset?

**Comment by Espere-1119-Song** [comment]
We have released both the [Train Set](https://huggingface.co/datasets/Enxin/MovieChat-1K_train) and the [Test Set](https://huggingface.co/datasets/Enxin/MovieChat-1K-test) of MovieChat-1K.

**Comment by zpx01** [comment]
@Espere-1119-Song Is the train set still only the CLIP features? Is there any plan to release the full videos?

**Comment by Espere-1119-Song** [comment]
Due to copyright restrictions, we share the clip features extracted by [eva_vit_g](https://www.google.com/url?q=https%3A%2F%2Fstorage.googleapis.com%2Fsfr-vision-language-research%2FLAVIS%2Fmodels%2FBLIP2%2Feva_vit_g.pth&sa=D), containing 8192 frames of each video.

**Comment by patrick-tssn** [comment]
> Due to copyright restrictions, we share the clip features extracted by [eva_vit_g](https://www.google.com/url?q=https%3A%2F%2Fstorage.googleapis.com%2Fsfr-vision-language-research%2FLAVIS%2Fmodels%2FBLIP2%2Feva_vit_g.pth&sa=D), containing 8192 frames of each video.

Does this mean that the complete videos or the extracted frames will never be released at any point in the future?

**Comment by Espere-1119-Song** [comment]
we release complete videos in the test set. For the train set, we only release the extracted frame feature and may not release the raw videos in the future.

**Comment by patrick-tssn** [comment]
> we release complete videos in the test set. For the train set, we only release the extracted frame feature and may not release the raw videos in the future.

I understand the situation; nevertheless, I extend my sincere thanks for all of your insightful contributions.

**Comment by hkunzhe** [comment]
> we release complete videos in the test set. For the train set, we only release the extracted frame feature and may not release the raw videos in the future.
@Espere-1119-Song, Congratulations on the nice work! Could you just give the name of the movie in the training set and the start time and end time of the video clip?

**Comment by Espere-1119-Song** [comment]
Sorry, when we collect video clips, we didn't record the name of the movie, the start time, and the end time of the video clip in the training set.

**Comment by zpx01** [comment]
> Sorry, when we collect video clips, we didn't record the name of the movie, the start time, and the end time of the video clip in the training set.

@Espere-1119-Song can you share exactly what websites these clips were downloaded from? Were they downloads from Youtube or some other source?

**Comment by Espere-1119-Song** [comment]
We collect them from Youtube

**Comment by sunwhw** [comment]
> We collect them from Youtube

Hi, Can you give me these youtube links to your video data? I can download it myself to comply with copyright restrictions.

**Comment by Espere-1119-Song** [comment]
Sorry, when we collected the videos, we didn't record the Youtube links. Besides, we cut the long videos to short clips (around 10 minutes).

**Comment by ADiko1997** [comment]
How do you download the dataset from the huggingface, I am having errors when generating the files

**Comment by Espere-1119-Song** [comment]
Hi, can you point out the specific error file or its folder? and we will check it

**Comment by ADiko1997** [comment]
Hi, the error i am getting is the following:  raise DatasetGenerationError("An error occurred while generating the dataset") from e
datasets.exceptions.DatasetGenerationError: An error occurred while generating the dataset

Following is the full error:
```
Resolving data files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1609/1609 [00:00<00:00, 1939.50it/s]
Downloading data: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 830/830 [00:00<00:00, 5060.72files/s]
Generating train split: 317 examples [00:00, 640.80 examples/s]
Traceback (most recent call last):
  File "/mnt/largedatavolume/wassim/.conda/envs/lavis/lib/python3.12/site-packages/datasets/builder.py", line 2013, in _prepare_split_single
    writer.write_table(table)
  File "/mnt/largedatavolume/wassim/.conda/envs/lavis/lib/python3.12/site-packages/datasets/arrow_writer.py", line 585, in write_table
    pa_table = table_cast(pa_table, self._schema)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/largedatavolume/wassim/.conda/envs/lavis/lib/python3.12/site-packages/datasets/table.py", line 2281, in table_cast
    return cast_table_to_schema(table, schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/largedatavolume/wassim/.conda/envs/lavis/lib/python3.12/site-packages/datasets/table.py", line 2240, in cast_table_to_schema
    arrays = [cast_array_to_feature(table[name], feature) for name, feature in features.items()]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/largedatavolume/wassim/.conda/envs/lavis/lib/python3.12/site-packages/datasets/table.py", line 1795, in wrapper
    return pa.chunked_array([func(chunk, *args, **kwargs) for chunk in array.chunks])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/largedatavolume/wassim/.conda/envs/lavis/lib/python3.12/site-packages/datasets/table.py", line 2006, in cast_array_to_feature
    arrays = [_c(array.field(name), subfeature) for name, subfeature in feature.items()]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/largedatavolume/wassim/.conda/envs/lavis/lib/python3.12/site-packages/datasets/table.py", line 1797, in wrapper
    return func(array, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/largedatavolume/wassim/.conda/envs/lavis/lib/python3.12/site-packages/datasets/table.py", line 2098, in cast_array_to_feature
    return array_cast(
           ^^^^^^^^^^^
  File "/mnt/largedatavolume/wassim/.conda/envs/lavis/lib/python3.12/site-packages/datasets/table.py", line 1797, in wrapper
    return func(array, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/largedatavolume/wassim/.conda/envs/lavis/lib/python3.12/site-packages/datasets/table.py", line 1949, in array_cast
    return array.cast(pa_type)
           ^^^^^^^^^^^^^^^^^^^
  File "pyarrow/array.pxi", line 1000, in pyarrow.lib.Array.cast
  File "/mnt/largedatavolume/wassim/.conda/envs/lavis/lib/python3.12/site-packages/pyarrow/compute.py", line 405, in cast
    return call_function("cast", [arr], options, memory_pool)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/_compute.pyx", line 590, in pyarrow._compute.call_function
  File "pyarrow/_compute.pyx", line 385, in pyarrow._compute.Function.call
  File "pyarrow/error.pxi", line 155, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Float value 23.98 was truncated converting to int64

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/largedatavolume/wassim/.conda/envs/lavis/lib/python3.12/site-packages/datasets/load.py", line 2628, in load_dataset
    builder_instance.download_and_prepare(
  File "/mnt/largedatavolume/wassim/.conda/envs/lavis/lib/python3.12/site-packages/datasets/builder.py", line 1029, in download_and_prepare
    self._download_and_prepare(
  File "/mnt/largedatavolume/wassim/.conda/envs/lavis/lib/python3.12/site-packages/datasets/builder.py", line 1124, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/mnt/largedatavolume/wassim/.conda/envs/lavis/lib/python3.12/site-packages/datasets/builder.py", line 1884, in _prepare_split
    for job_id, done, content in self._prepare_split_single(
  File "/mnt/largedatavolume/wassim/.conda/envs/lavis/lib/python3.12/site-packages/datasets/builder.py", line 2040, in _prepare_split_single
    raise DatasetGenerationError("An error occurred while generating the dataset") from e
datasets.exceptions.DatasetGenerationError: An error occurred while generating the dataset

```

**Comment by Espere-1119-Song** [comment]
We didn't meet this error before. Perhaps you can use `git clone` to download MovieChat-1k.

**Comment by ADiko1997** [comment]
I was Able to download it now, it works with and without git, the issue seemed to be the proxy though i do not understand why that error. Thank you very much.
